version: "{build}"

image: Visual Studio 2017

clone_folder: c:\stackless

build_script:
  - git clone https://github.com/stackless-dev/stackless.git
  - git clone https://github.com/stackless-dev/stackman.git
  - cmd: dir stackless
  - cmd: dir stackless\stackless

  - cmd: stackless\PCbuild\build.bat -e -p x64
  - cmd: stackless\PCbuild\amd64\python.exe -m test.pythoninfo
test_script:
  - cmd: stackless\stackless\PCbuild\rt.bat -x64 -q -uall -u-cpu -u-largefile -rwW --slowest --timeout=1200 --fail-env-changed -j0
environment:
  HOST_PYTHON: C:\Python36\python.exe
