image: Visual Studio 2019

install:
  - choco install git nasm -y
  - git --version
  - nasm -v

build_script:
  - git clone https://github.com/stackless-dev/stackless.git
  - cd stackless
  - cd PCbuild
  - call build.bat -e
  - cd ..
  - PCbuild\python.exe -m test
